### SIGNUP BUANA
post http://localhost:8000/user/register
Content-Type: application/json

{
    "username": "Clare Wangari",
    "email":"Wangari@gmail.com",
    "password": "@Wangari56"
}

### LOGIN BUANA
post http://localhost:8000/user/login
Content-Type: application/json

{
    "email":"Wangari@gmail.com",
    "password": "@Wangari56"
}


### FOLLOW BUANA EIH
post http://localhost:8000/user/follow
Content-Type: application/json

{
  "user_id": "25b11e35-5dcf-4842-ae48-8dc34b122285",
  "follower_user_id": "f1074272-73b7-42af-8cf8-b9aa408f4ca4"
}


### GET THEM ALL BUANA
GET http://localhost:8000/user/all
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlNGNlMWFmZS1mOWFmLTQ5N2MtYjA4Ni00YmNjNDJhYTAxNTgiLCJlbWFpbCI6ImVtbWFudWVsQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRW1tYW51ZWwgS2lwc2FuZyIsImlhdCI6MTcwMjQ5ODA2MywiZXhwIjoxNzAyNjcwODYzfQ.Qlg7aWptOKA2DcBj3ImL-p0yb1RmKDKOw_MWfjtFapo 


### CREATE POST BUANA EIH
post http://localhost:8000/post/create
Content-Type: application/json

{
  "post_description": "Kitheka",
  "post_image": "https://www.pinterest.com/pin/1150880879748603683/",
  "user_id": "d2bfcf22-6e0c-4ec8-9515-c53c099c67e3"
}


### COMMENT BUANA COMMENT
post http://localhost:8000/comment/add
Content-Type: application/json

{
  "user_id": "25b11e35-5dcf-4842-ae48-8dc34b122285",
  "post_id": "e5c237f9-45dd-4ded-9b4f-b74f6285e957",
  "comment_text": "It is yet another Beautiful morning"
}


### UPDATE COMMENT BUANA
PUT http://localhost:8000/comment/update/
Content-Type: application/json

{
  "comment_id": "eb962388-0908-476f-9f62-97e55e5b3e39",
  "comment_text": "Good boy"
}


### LIKE THE POST BUANA
post http://localhost:8000/like/like
Content-Type: application/json

{
  "user_id": "25b11e35-5dcf-4842-ae48-8dc34b122285",
  "post_id": "e5c237f9-45dd-4ded-9b4f-b74f6285e957"

}



### DELETE POST BUANA - HARAM!
delete http://localhost:8000/post/e5c237f9-45dd-4ded-9b4f-b74f6285e957
Content-Type: application/json


### GET ALL POSTS
GET http://localhost:8000/post/all
Content-Type: application/json


### GET ONE POST
GET http://localhost:8000/post/a6e3c6ca-4d78-4ed0-99a6-232f4841bf43
Content-Type: application/json


### GET FOLLOWERS BUANA
GET http://localhost:8000/user/25b11e35-5dcf-4842-ae48-8dc34b122285/followers
Content-Type: application/json
token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4OWEyNDhkMy0zZjFmLTRhNDgtYTcwYS0zMjkwYjM1MDU2MmYiLCJlbWFpbCI6ImFzYW1hbkBnbWFpbC5jb20iLCJ1c2VybmFtZSI6IlBlcmV6IEFubmFuIiwiaWF0IjoxNzAyNjM0MzA0LCJleHAiOjE3MDI4MDcxMDR9.6_ciRhcN53vq6DmlwR4G_YvNXW7LKqVeIdkyGpBA3pE"


# ### GET All THEM COMMENTS ALL BUANA
###
GET http://localhost:8000/post/comment/a6e3c6ca-4d78-4ed0-99a6-232f4841bf43
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlNGNlMWFmZS1mOWFmLTQ5N2MtYjA4Ni00YmNjNDJhYTAxNTgiLCJlbWFpbCI6ImVtbWFudWVsQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiRW1tYW51ZWwgS2lwc2FuZyIsImlhdCI6MTcwMjQ5ODA2MywiZXhwIjoxNzAyNjcwODYzfQ.Qlg7aWptOKA2DcBj3ImL-p0yb1RmKDKOw_MWfjtFapo 


### GET ONE USER
GET http://localhost:8000/user/25b11e35-5dcf-4842-ae48-8dc34b122285
Content-Type: application/json
